[workspace]
members = [
    "openmls",
    "traits",
    "openmls_rust_crypto",
    "fuzz",
    "cli",
    # "interop_client",
    "memory_keystore",
    "delivery-service/ds",
    "delivery-service/ds-lib",
    "basic_credential",
    "x509_credential"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1"

[workspace.dependencies.tls_codec]
version = "0.3.0-pre.3"
features = ["derive", "serde", "mls"]
git = "https://github.com/RustCrypto/formats.git"
package = "tls_codec"
ref = "2fcc4599"

[workspace.dependencies.tls_codec_derive]
version = "0.3.0-pre.3"
features = ["derive", "serde", "mls"]
git = "https://github.com/RustCrypto/formats.git"
package = "tls_codec/derive"
ref = "2fcc4599"
