[workspace]
members = [
    "openmls",
    "traits",
    "openmls_rust_crypto",
    "fuzz",
    "cli",
    # "interop_client",
    "memory_keystore",
    "delivery-service/ds",
    "delivery-service/ds-lib",
    "basic_credential"
]
resolver = "2"

[workspace.dependencies]
tls_codec = { version = "0.3.0-pre.3", features = ["derive", "serde", "mls"] }
async-trait = "0.1"
