name: test coverage

on:
  - push

jobs:
  check:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc, rust-std, cargo, llvm-tools, llvm-tools-preview
          run:
      - uses: Swatinem/rust-cache@v2
      - name: Install grcov
        run: cargo install grcov
      - name: Run profiling tests
        run: |
          mkdir -p target/debug/coverage
          cargo test --no-fail-fast -p openmls
        env:
          CARGO_INCREMENTAL: '0'
          LLVM_PROFILE_FILE: 'target/debug/coverage/openmls-%p-%m.profraw'
          RUSTFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: Run grcov
        id: coverage
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/debug/coverage/

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: target/debug/coverage/lcov
